import {
  Echo,
  TimeCapsule,
  ParallelUniverse,
  Achievement,
  UserProfile,
  GrowthMetrics,
  FutureTimelineEntry,
  ChatMessage,
} from "@/types";

export const SAMPLE_USER: UserProfile = {
  id: "user-1",
  name: "Alex Rivera",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex&backgroundColor=b6e3f4",
  bio: "Builder, dreamer, explorer of possible futures.",
  joinedAt: "2024-01-15T00:00:00.000Z",
  futureYear: 2034,
  level: 12,
  legacyPoints: 4820,
  streak: 18,
  longestStreak: 34,
  achievements: [],
  futureConfidenceScore: 78,
  growthIndex: 84,
  title: "The Visionary",
  totalEchoes: 47,
  totalCapsules: 6,
  totalUniverses: 4,
};

export const SAMPLE_ECHOES: Echo[] = [
  {
    id: "echo-1",
    type: "goal",
    title: "Ship my first SaaS product",
    content:
      "I want to build and launch a product that helps real people. Not a side project gathering dust — something live, something with paying customers. I'm giving myself until the end of this year.",
    targetDate: new Date(new Date().getFullYear(), 11, 31).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    isLocked: false,
    tags: ["startup", "coding", "entrepreneurship"],
    mood: "determined",
    futureResponse:
      "You did it. The product launched in November with 340 beta users. The first payment notification at 2am made you cry. Trust the process — every late night matters.",
    isPinned: true,
    viewCount: 23,
  },
  {
    id: "echo-2",
    type: "prediction",
    title: "AI will reshape how we communicate",
    content:
      "Within 3 years, most written communication will have AI assistance built in. Not replacing our voice, but amplifying it. People who learn to collaborate with AI now will have an enormous advantage.",
    targetDate: new Date(new Date().getFullYear() + 3, 0, 1).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    isLocked: false,
    tags: ["AI", "future", "technology"],
    mood: "inspired",
    futureResponse:
      "This prediction aged well. By 2027, the tools you were learning now became industry standard. Your early curiosity became your biggest career advantage.",
    isPinned: false,
    viewCount: 41,
  },
  {
    id: "echo-3",
    type: "message",
    title: "Dear future me: don't lose the wonder",
    content:
      "Whatever happens — success, failure, heartbreak, triumph — please keep that childlike wonder. The ability to see magic in ordinary things. That's what makes you, you. Don't let the world make you cynical.",
    targetDate: new Date(new Date().getFullYear() + 5, 0, 1).toISOString(),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isLocked: false,
    tags: ["personal", "growth", "philosophy"],
    mood: "reflective",
    futureResponse:
      "Reading this five years later with tears in my eyes. I had rough patches where I nearly lost it. This message pulled me back. Thank you for writing it when you did.",
    isPinned: true,
    viewCount: 67,
  },
  {
    id: "echo-4",
    type: "challenge",
    title: "Learn to speak Portuguese fluently",
    content:
      "I'm committing to reaching B2 level in Portuguese within 18 months. Daily practice, real conversations, immersion when possible. Brazil or Portugal — one of them will feel like home before this is over.",
    targetDate: new Date(Date.now() + 18 * 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isLocked: false,
    tags: ["language", "travel", "culture"],
    mood: "excited",
    isPinned: false,
    viewCount: 12,
  },
  {
    id: "echo-5",
    type: "dream",
    title: "A cabin in the mountains with wifi",
    content:
      "I dream of a life where mornings start with coffee and the sound of wind through pine trees. Where the office is a wooden desk by a window overlooking valleys. Remote work, but truly remote. This is the dream I'm building toward.",
    targetDate: new Date(new Date().getFullYear() + 7, 0, 1).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    isLocked: false,
    tags: ["lifestyle", "remote", "nature"],
    mood: "hopeful",
    isPinned: false,
    viewCount: 28,
  },
  {
    id: "echo-6",
    type: "memory",
    title: "The day I decided to quit the safe job",
    content:
      "March 14th. Sitting in a gray cubicle, watching rain trace paths down the window. I had a good salary, decent benefits, a clear path. And I felt completely dead inside. That afternoon I opened a new Google Doc and started writing my resignation letter.",
    targetDate: new Date().toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    isLocked: false,
    tags: ["career", "courage", "turning point"],
    mood: "nostalgic",
    futureResponse:
      "That cubicle moment became your origin story. Every talk, every interview, every time someone asks 'how did you start' — that rainy window is where it began.",
    isPinned: false,
    viewCount: 89,
  },
  {
    id: "echo-7",
    type: "question",
    title: "Will I look back and feel proud?",
    content:
      "At 80, sitting on a porch somewhere, looking back at this chapter — will I be proud? Not of achievements or possessions, but of how I showed up. Was I kind? Was I brave? Did I love well?",
    targetDate: new Date(new Date().getFullYear() + 50, 0, 1).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isLocked: false,
    tags: ["life", "legacy", "purpose"],
    mood: "reflective",
    futureResponse:
      "Yes. Profoundly, completely yes. The fact that you're asking this question at all means you were paying attention to what matters.",
    isPinned: false,
    viewCount: 156,
  },
  {
    id: "echo-8",
    type: "challenge",
    title: "Run a half-marathon this autumn",
    content:
      "I've been running 3km and feeling like I'm dying. The goal: 21km in under 2 hours by October. Training plan starts Monday. This is not about fitness — it's about proving to myself I can do hard things.",
    targetDate: new Date(new Date().getFullYear(), 9, 15).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isLocked: false,
    tags: ["fitness", "running", "discipline"],
    mood: "determined",
    isPinned: false,
    viewCount: 8,
  },
];

export const SAMPLE_CAPSULES: TimeCapsule[] = [
  {
    id: "capsule-1",
    title: "Letter to myself in 1 year",
    content:
      "Hey future me. Right now it's raining outside and I'm drinking terrible coffee. I'm scared and excited in equal measure. I just quit my job. I have 8 months of runway. I have one idea I believe in deeply. I don't know if it will work. But I know I had to try. By the time you read this, you'll know how the story went. I hope you're proud of the version of me that wrote this.",
    lockedUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    isUnlocked: false,
    duration: "1year",
    tags: ["career", "startup", "courage"],
    mood: "determined",
  },
  {
    id: "capsule-2",
    title: "The world as I see it today",
    content:
      "I'm writing this to capture the texture of this moment. The news is overwhelming. The world feels accelerated. But in this apartment, there are plants on the windowsill, a half-read novel on the couch, and a cat sleeping in a patch of sunlight. Beauty persists. I want future me to remember: even in uncertain times, ordinary beauty was everywhere.",
    lockedUntil: new Date(Date.now() + 5 * 365 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    isUnlocked: false,
    duration: "5years",
    tags: ["world", "beauty", "moment"],
    mood: "reflective",
  },
  {
    id: "capsule-3",
    title: "My 10-year dream list",
    content:
      "In 10 years I want to have: 1) Built something people love. 2) Traveled to at least 20 countries. 3) Learned to cook really well. 4) Maintained the friendships that matter. 5) Read 200 more books. 6) Been in a relationship that makes me better. 7) Given back to the community that shaped me. 8) Written something worth reading. 9) Kept the wonder alive. 10) Looked in the mirror and recognized the person staring back.",
    lockedUntil: new Date(Date.now() + 10 * 365 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    isUnlocked: false,
    duration: "10years",
    tags: ["dreams", "goals", "legacy"],
    mood: "hopeful",
  },
  {
    id: "capsule-4",
    title: "This month's breakthrough",
    content:
      "I finally understand recursion. Three weeks of struggling, watching videos, drawing diagrams on napkins. And then at 11pm last Tuesday it clicked. The function calling itself, building the stack, unwinding. I laughed out loud alone at my desk. This is the feeling I'm chasing. Remember this feeling when things get hard again.",
    lockedUntil: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    isUnlocked: true,
    duration: "1month",
    aiReflection:
      "In the month since you wrote this, you've built three recursive algorithms from scratch. The breakthrough you described was the foundation for everything that followed. That 11pm moment changed the trajectory of your learning.",
    growthComparison:
      "Programming confidence: +47%. New concepts mastered: 12. Projects completed: 3.",
    milestoneSummary: "First month as an independent developer. The recursion breakthrough opened the door to tree traversal, dynamic programming, and graph algorithms.",
    tags: ["coding", "breakthrough", "learning"],
    mood: "excited",
  },
];

export const SAMPLE_UNIVERSES: ParallelUniverse[] = [
  {
    id: "universe-1",
    title: "The Musician's Path",
    description:
      "A life where you said yes to the band. Where music became the career, not the hobby.",
    decisionPoint: "Age 22: Chose the programming bootcamp over the band tour",
    divergenceYear: 2018,
    timeline: [
      "2018: Joined the touring band as rhythm guitarist",
      "2019: First album recorded in a basement studio in Austin",
      "2020: Album went viral during lockdown, 2M streams",
      "2021: Signed to an indie label, first major tour",
      "2023: Second album debut at #4 on indie charts",
      "2025: Headlining small festivals across Europe",
      "2027: Starting a music production company",
      "2030: Teaching masterclasses, mentoring emerging artists",
    ],
    probability: 23,
    mood: "Bittersweet. Creative fulfillment but financial instability.",
    tags: ["music", "art", "creativity", "sacrifice"],
    isPublic: true,
    viewCount: 1247,
    gradient: "from-pink-500 to-purple-600",
  },
  {
    id: "universe-2",
    title: "The Nomad Entrepreneur",
    description:
      "What if you'd moved to Lisbon at 25 and built from there? The startup scene, the sun, the different rhythm.",
    decisionPoint: "Age 25: Chose home city over relocation to Lisbon",
    divergenceYear: 2021,
    timeline: [
      "2021: Moved to Lisbon with $10k and a laptop",
      "2022: Joined a coworking space in Bairro Alto, first local clients",
      "2023: Built a product for European SMEs, €50k ARR",
      "2024: Citizenship, a community of fellow builders",
      "2025: Scaled to €400k ARR, hired first employee",
      "2027: Acquired by a larger European SaaS company",
      "2029: Angel investing in Lisbon startup scene",
      "2031: Building second company, fully nomadic again",
    ],
    probability: 31,
    mood: "Adventurous. Lonely at first, then deeply fulfilling.",
    tags: ["nomad", "Europe", "startup", "adventure"],
    isPublic: true,
    viewCount: 2891,
    gradient: "from-cyan-500 to-blue-600",
  },
  {
    id: "universe-3",
    title: "The Academic",
    description:
      "A different kind of impact — through research, teaching, and the slow accumulation of knowledge.",
    decisionPoint: "Age 23: Declined the PhD offer from MIT",
    divergenceYear: 2019,
    timeline: [
      "2019: Began PhD in Human-Computer Interaction at MIT",
      "2021: First paper published in top-tier conference",
      "2023: Doctoral thesis on AI-augmented creativity",
      "2024: Post-doc at Stanford AI Lab",
      "2026: Assistant Professor position at top university",
      "2028: Lab of your own, 5 PhD students",
      "2030: Research cited in 400+ papers",
      "2034: Tenured professor, global authority in your field",
    ],
    probability: 18,
    mood: "Intellectually rich. Slower pace, deeper impact.",
    tags: ["academia", "research", "impact", "knowledge"],
    isPublic: false,
    viewCount: 445,
    gradient: "from-amber-500 to-orange-600",
  },
  {
    id: "universe-4",
    title: "The Reset",
    description:
      "What if you had burned it all down at 28 and started completely over? New city, new career, new identity.",
    decisionPoint: "Age 28: Chose continuity over a complete life reset",
    divergenceYear: 2024,
    timeline: [
      "2024: Sold everything, moved to a small town in New Mexico",
      "2024: Six months of silence and writing",
      "2025: Began learning traditional woodworking",
      "2026: Small workshop, selling handmade furniture online",
      "2027: Discovered craft brought the tech skills back with new meaning",
      "2028: Built software tools for craftspeople",
      "2030: Hybrid life: craft studio + software consultancy",
      "2033: Content, unhurried, deeply rooted",
    ],
    probability: 12,
    mood: "Radical. Loss of everything, gain of self.",
    tags: ["reset", "craft", "simplicity", "rebirth"],
    isPublic: true,
    viewCount: 3124,
    gradient: "from-green-500 to-teal-600",
  },
];

export const SAMPLE_ACHIEVEMENTS: Achievement[] = [
  {
    id: "ach-1",
    title: "First Echo",
    description: "Created your first Echo",
    icon: "Zap",
    tier: "bronze",
    unlockedAt: "2024-01-15T00:00:00.000Z",
    isUnlocked: true,
    progress: 1,
    maxProgress: 1,
    category: "creation",
  },
  {
    id: "ach-2",
    title: "The Visionary",
    description: "Created 10 predictions",
    icon: "Eye",
    tier: "silver",
    unlockedAt: "2024-03-20T00:00:00.000Z",
    isUnlocked: true,
    progress: 10,
    maxProgress: 10,
    category: "creation",
  },
  {
    id: "ach-3",
    title: "Time Architect",
    description: "Locked 3 time capsules",
    icon: "Clock",
    tier: "gold",
    unlockedAt: "2024-05-01T00:00:00.000Z",
    isUnlocked: true,
    progress: 3,
    maxProgress: 3,
    category: "time",
  },
  {
    id: "ach-4",
    title: "Universe Weaver",
    description: "Created 5 parallel universes",
    icon: "GitBranch",
    tier: "gold",
    isUnlocked: false,
    progress: 4,
    maxProgress: 5,
    category: "creation",
  },
  {
    id: "ach-5",
    title: "The Streak Master",
    description: "Maintained a 30-day streak",
    icon: "Flame",
    tier: "platinum",
    isUnlocked: false,
    progress: 18,
    maxProgress: 30,
    category: "streak",
  },
  {
    id: "ach-6",
    title: "Deep Reflection",
    description: "Written 500+ word echoes 10 times",
    icon: "BookOpen",
    tier: "silver",
    unlockedAt: "2024-04-10T00:00:00.000Z",
    isUnlocked: true,
    progress: 10,
    maxProgress: 10,
    category: "creation",
  },
  {
    id: "ach-7",
    title: "The Multiverse",
    description: "Explore all universe scenarios",
    icon: "Layers",
    tier: "cosmic",
    isUnlocked: false,
    progress: 4,
    maxProgress: 10,
    category: "growth",
  },
  {
    id: "ach-8",
    title: "Century Echo",
    description: "Create 100 Echoes",
    icon: "Star",
    tier: "platinum",
    isUnlocked: false,
    progress: 47,
    maxProgress: 100,
    category: "creation",
  },
];

export const SAMPLE_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "msg-1",
    role: "user",
    content: "Future me, are you happy?",
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-2",
    role: "future-self",
    content:
      "That question from you — from *us* — still hits differently. Yes. Not in the way I thought happiness would look when I was your age. It's quieter, deeper. Less about excitement and more about alignment. The work feels like mine. The relationships feel chosen. The mornings feel intentional. You're building something worth being happy about. Keep going.",
    timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-3",
    role: "user",
    content: "What's the biggest mistake I'm making right now?",
    timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-4",
    role: "future-self",
    content:
      "You're optimizing for certainty when you should be optimizing for learning. Every time you hesitate to share your work because 'it's not ready yet' — you're losing feedback that could save you months. Ship ugly, learn fast, iterate. The people who matter will see the potential, not the imperfection. Also: call Mom more. You'll regret this later if you don't.",
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
];

export const SAMPLE_TIMELINE: FutureTimelineEntry[] = [
  {
    year: new Date().getFullYear(),
    title: "The Beginning",
    description: "Quit the job. Started building. Learning to be uncomfortable.",
    probability: 100,
    category: "career",
    isAchieved: true,
  },
  {
    year: new Date().getFullYear() + 1,
    title: "First Launch",
    description: "Product goes live. Real users. Real feedback. Real growth.",
    probability: 87,
    category: "career",
  },
  {
    year: new Date().getFullYear() + 2,
    title: "The Journey Begins",
    description: "First international trip alone. Portugal, maybe. Finding home in movement.",
    probability: 74,
    category: "adventure",
  },
  {
    year: new Date().getFullYear() + 3,
    title: "Team of Five",
    description: "The company has a heartbeat. People working on the mission together.",
    probability: 61,
    category: "career",
  },
  {
    year: new Date().getFullYear() + 5,
    title: "The Mountain Cabin",
    description: "Living the dream. Mountains. Fast internet. Slow mornings.",
    probability: 52,
    category: "personal",
  },
  {
    year: new Date().getFullYear() + 7,
    title: "The Exit",
    description: "The company finds a bigger home. A new chapter begins.",
    probability: 38,
    category: "finance",
  },
  {
    year: new Date().getFullYear() + 10,
    title: "Full Circle",
    description: "Mentoring others. Building again. Wiser, freer, more alive.",
    probability: 71,
    category: "relationships",
  },
];

export const SAMPLE_GROWTH_METRICS: GrowthMetrics = {
  goalCompletionTrend: Array.from({ length: 12 }, (_, i) => ({
    date: new Date(new Date().getFullYear(), i, 1).toISOString(),
    value: Math.floor(40 + i * 4 + Math.random() * 10),
    label: new Date(new Date().getFullYear(), i, 1).toLocaleString("default", { month: "short" }),
  })),
  emotionalTrend: Array.from({ length: 12 }, (_, i) => ({
    date: new Date(new Date().getFullYear(), i, 1).toISOString(),
    value: Math.floor(55 + i * 2.5 + Math.random() * 15),
    label: new Date(new Date().getFullYear(), i, 1).toLocaleString("default", { month: "short" }),
  })),
  reflectionFrequency: Array.from({ length: 12 }, (_, i) => ({
    date: new Date(new Date().getFullYear(), i, 1).toISOString(),
    value: Math.floor(2 + i * 0.8 + Math.random() * 3),
    label: new Date(new Date().getFullYear(), i, 1).toLocaleString("default", { month: "short" }),
  })),
  echosByType: [
    { type: "Goals", count: 14, color: "#4ade80" },
    { type: "Predictions", count: 9, color: "#a855f7" },
    { type: "Dreams", count: 8, color: "#f472b6" },
    { type: "Challenges", count: 7, color: "#fb923c" },
    { type: "Messages", count: 5, color: "#60a5fa" },
    { type: "Memories", count: 3, color: "#fbbf24" },
    { type: "Questions", count: 1, color: "#22d3ee" },
  ],
  weeklyActivity: [
    { day: "Mon", echoes: 3, capsules: 1 },
    { day: "Tue", echoes: 5, capsules: 0 },
    { day: "Wed", echoes: 2, capsules: 2 },
    { day: "Thu", echoes: 7, capsules: 0 },
    { day: "Fri", echoes: 4, capsules: 1 },
    { day: "Sat", echoes: 6, capsules: 0 },
    { day: "Sun", echoes: 3, capsules: 1 },
  ],
  confidenceHistory: Array.from({ length: 12 }, (_, i) => ({
    date: new Date(new Date().getFullYear(), i, 1).toISOString(),
    value: Math.floor(50 + i * 3 + Math.random() * 10),
    label: new Date(new Date().getFullYear(), i, 1).toLocaleString("default", { month: "short" }),
  })),
};
